# -*- encoding: utf-8 -*-
###########################################################################
#
#    Copyright (C) 2009 Sandas. (http://www.sandas.eu) All Rights Reserved.
#
###########################################################################

{
    'name': 'Sanitex Delivery',
    'version': '1.0',
    'category': 'Sales Management',
    'sequence': 14,
    'summary': 'Sanitex Delivery',
    'description': """""",
    'author': 'Sandas',
    'images': ['images/Sale_order_line_to_invoice.jpeg','images/sale_order.jpeg','images/sales_analysis.jpeg'],
    'depends': ['sale','stock', 'sale_stock', 'sandas_maintenance'],
    'data': [
        'security/new_groups.xml',
        'views/base.xml',
        'views/webclient_templates.xml',
        # 'views/assets.xml',
        'wizard/stock_route_select_orders_view.xml',
        'wizard/stock_route_transfer_product_view.xml',
        'wizard/stock_route_transfer_orders_view.xml',
        # 'stock_report_date.xml',
        'wizard/stock_route_return_packing_from_driver_view.xml',
        'wizard/stock_route_get_orders_view.xml',
        'wizard/stock_route_select_driver_view.xml',
        'wizard/stock_route_select_product_view.xml',
        'wizard/stock_route_transfer_product_to_wh_view.xml',
        'wizard/stock_route_confirm_selected_packings_view.xml',
        'wizard/stock_location_change_owner_view.xml',
        # 'wizard/stock_package_assign_to_route_view.xml',
        'wizard/stock_location_import_view.xml',
        'wizard/integration_process_multiple_view.xml',
        'wizard/stock_location_import_driver_qty_view.xml',
        'wizard/account_invoice_container_change_state_view.xml',
        'wizard/sale_order_create_route_view.xml',
        # 'wizard/stock_route_release_select_warehouses_view.xml',
        'wizard/stock_route_release_select_intermediate_warehouse_view.xml',
        'account_view.xml',
        'wizard/stock_route_add_remove_tare_view.xml',
        'stock_view.xml',
        # 'wizard/integration_open_objects_view.xml',
        'wizard/recalculate_stocks_view.xml',
        # 'wizard/res_users_select_default_warehouse_view.xml',
        # 'wizard/res_users_select_default_printer_view.xml',
        'sale_view.xml',
        'stock_report.xml',
        'settings_view.xml',
        'wizard/stock_route_print_packing_report_view.xml',
        'wizard/stock_route_print_report_view.xml',
        'wizard/stock_correction_report_print_view.xml',
        # 'wizard/stock_route_release_warning_view.xml',
        'company_view.xml',
        'stock_data.xml',
        'integration_view.xml',
        'integration_data.xml',
        'ir_sequence_data.xml',
        'product_view.xml',
        'res_partner_view.xml',
        'actions_view.xml',
        'user_view.xml',
        'security/ir.model.access.csv',
        'report_view.xml',
        'translations.xml',
        'settings_data.xml',
        'wizard/stock_route_receive_partly_view.xml',
        'transportation_view.xml',
        'company_data.xml',
        'wizard/settings_run_function_view.xml',
        'report/report_stock_correction.xml',
        'report/packing_return_act.xml',
        'action_queue_view.xml',
        'action_queue_data.xml',
        'route_template_view.xml',
        'sale_data.xml',
        'wizard/object_confirm_action_view.xml',
        'wizard/change_password_view.xml',
        'report/return_from_driver_act.xml',
        'wizard/sale_order_assign_route_temlpate_view.xml',
        'document_view.xml',
        'internal_operation_view.xml',
        'wizard/print_report_from_object_view.xml',
        'internal_operation_report.xml',
        'internal_operation_data.xml',
        'language_data.xml',
        'language_view.xml',
        'sequence_view.xml',
        'wizard/stock_route_document_check_up_view.xml',
        'account_report.xml',
        'product_data.xml'
    ],
    'demo': [],
    'test': [],
    'qweb': [
        'static/src/xml/systray.xml',
        'static/src/xml/base.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}